name: dialects

on:
  schedule:
  - cron: '4 5 * * *'
  workflow_dispatch:

jobs:
  dialects:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - run: cd / && go install mvdan.cc/gofumpt@v0.3.1

    - run: make dialects-nodocker

    - run: |
        test -z "$(git status --porcelain)" ||
        ( make test-nodocker \
        && git add . \
        && REV=$(curl -sL https://api.github.com/repos/mavlink/mavlink/branches/master | jq -r '.commit.sha') \
        && git config user.name gomavlib-bot \
        && git config user.email bot@gomavlib \
        && git commit -m "(automatic) update dialects to rev https://github.com/mavlink/mavlink/tree/${REV}" \
        && git push )
